openapi: 3.0.3
info:
  title: Local Azure Speech Diarization Proxy
  version: 0.1.0
  description: |
    Contract for the CLI's interaction with the local Azure Speech-to-Text preview container.
servers:
  - url: http://localhost:5000
    description: Default port exposed by the Speech container inside devcontainer network.
paths:
  /speech/recognition/conversation/diarize:
    post:
      summary: Submit audio for diarization
      description: >-
        Accepts a WAV audio stream and returns diarized speaker segments in JSON format.
      parameters:
        - in: query
          name: language
          required: true
          schema:
            type: string
            example: en-US
        - in: query
          name: format
          required: false
          schema:
            type: string
            default: detailed
      requestBody:
        required: true
        content:
          audio/wav:
            schema:
              type: string
              format: binary
            examples:
              sampleMeeting:
                summary: Multi-speaker meeting audio
                description: Sample file stored alongside the spec evidence.
      responses:
        '200':
          description: Diarization result
          content:
            application/json:
              schema:
                type: object
                properties:
                  recognitionStatus:
                    type: string
                  offset:
                    type: integer
                  duration:
                    type: integer
                  conversationTranscriptions:
                    type: array
                    items:
                      type: object
                      properties:
                        channel:
                          type: integer
                        speakerId:
                          type: string
                        text:
                          type: string
                        lexical:
                          type: string
                        itn:
                          type: string
                        confidence:
                          type: number
                        words:
                          type: array
                          items:
                            type: object
                            properties:
                              word:
                                type: string
                              offset:
                                type: integer
                              duration:
                                type: integer
        '400':
          description: Input validation error from the container
        '401':
          description: Billing key or region missing/incorrect
        '500':
          description: Container failure while processing audio
